server {
    # 1. Слушаем стандартный порт HTTPS
    listen 443 ssl;
    http2 on;
    server_name library.coventry.edu.kz;

    # 2. Пути к сертификатам
    ssl_certificate /etc/nginx/ssl/full_chain.crt;
    ssl_certificate_key /etc/nginx/ssl/private.key;

    # 3. Настройки шифрования (стандарт)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # --- КОНФИГУРАЦИЯ БЕЗОПАСНОСТИ ---
    # Мы убрали глобальные allow/deny, чтобы сайт был доступен всем.
    # Фильтрация теперь только внутри специфических location.

    # 4. ОБЩИЙ ДОСТУП (Сайт для всех)
    location / {
        proxy_pass http://127.0.0.1:8000;

        # Заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # 5. ОГРАНИЧЕННЫЙ ДОСТУП: Админка (/admin)
    location /admin {
        # === IP ФИЛЬТР ===
        allow 192.168.0.0/16;  # Локальные подсети
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        allow 127.0.0.1;
        deny all;              # Иначе 403 Forbidden

        # Проксируем запрос, если IP прошел проверку
        proxy_pass http://127.0.0.1:8000;

        # Te же заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # 6. ОГРАНИЧЕННЫЙ ДОСТУП: Сканер (/scan)
    location /scan {
        # === IP ФИЛЬТР ===
        allow 192.168.0.0/16;
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        allow 127.0.0.1;
        deny all;

        proxy_pass http://127.0.0.1:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Редирект с HTTP (80) на HTTPS (443)
server {
    listen 80;
    server_name library.coventry.edu.kz;
    return 301 https://$host$request_uri;
}
