import os
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("DB_PATH", "gateway.db")
ADMIN_PIN = os.getenv("ADMIN_PIN", "9876")
MAX_BOOKS = int(os.getenv("MAX_BOOKS", "5"))
MAX_DAYS = int(os.getenv("MAX_DAYS", "14"))
CARDCODE_PREFIX = os.getenv("CARDCODE_PREFIX", "21000000")
HEARTBEAT_SECONDS = int(os.getenv("APP_HEARTBEAT_SECONDS", "1800"))

EXPECTED_ACTIVATION_KEY = "AB2025-ELIBRA-MIDDLEWARE-AIDAR-BEGOTAYEV"
EXPECTED_ACTIVATION_PASSWORD = "AB2025-PROJECT"

APP_ACTIVATION_KEY = os.getenv("APP_ACTIVATION_KEY", "")
APP_ACTIVATION_PASSWORD = os.getenv("APP_ACTIVATION_PASSWORD", "")

DISCORD_STARTUP_WEBHOOK_URL = os.getenv("DISCORD_STARTUP_WEBHOOK_URL", "")
DISCORD_EVENTS_WEBHOOK_URL = os.getenv("DISCORD_EVENTS_WEBHOOK_URL", "") or DISCORD_STARTUP_WEBHOOK_URL


